# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbourhood', '0004_auto_20190325_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
