# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbourhood', '0005_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
