# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbourhood', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
